<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAyHnVHG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAyHnVHG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAyHnVHG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAyHnVHG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAyHnVHG\App_KernelDevDebugContainer([
    'container.build_hash' => 'AyHnVHG',
    'container.build_id' => '7eaa1f8f',
    'container.build_time' => 1577969069,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAyHnVHG');
